import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection, isDevMode } from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  LucideAngularModule,
  LayoutDashboard,
  ArrowLeftRight,
  Wallet,
  CreditCard,
  Tags,
  PieChart,
  Target,
  TrendingUp,
  CalendarDays,
  FileBarChart2,
  Sun,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Search,
  Landmark,
  PiggyBank,
  Banknote,
  Home,
  Utensils,
  Car,
  HeartPulse,
  PawPrint,
  Repeat,
  Gamepad2,
  ShoppingBag,
  GraduationCap,
  Popcorn,
  MoreHorizontal,
  Briefcase,
  User,
  Plus,
  Pencil,
  Trash2,
  X,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Download,
  Upload,
  Star,
  Copy,
  RotateCcw,
  Menu,
  FileSpreadsheet,
  LogOut,
  Layers,
  Users,
} from 'lucide-angular';

import { routes } from './app.routes';
import { provideServiceWorker } from '@angular/service-worker';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    importProvidersFrom(
      LucideAngularModule.pick({
        LayoutDashboard,
        ArrowLeftRight,
        Wallet,
        CreditCard,
        Tags,
        PieChart,
        Target,
        TrendingUp,
        CalendarDays,
        FileBarChart2,
        Sun,
        Moon,
        PanelLeftClose,
        PanelLeftOpen,
        Search,
        Landmark,
        PiggyBank,
        Banknote,
        Home,
        Utensils,
        Car,
        HeartPulse,
        PawPrint,
        Repeat,
        Gamepad2,
        ShoppingBag,
        GraduationCap,
        Popcorn,
        MoreHorizontal,
        Briefcase,
        User,
        Plus,
        Pencil,
        Trash2,
        X,
        Check,
        ChevronLeft,
        ChevronRight,
        ChevronDown,
        Download,
        Upload,
        Star,
        Copy,
        RotateCcw,
        Menu,
        FileSpreadsheet,
        LogOut,
        Layers,
        Users,
      }),
    ), provideServiceWorker('ngsw-worker.js', {
            enabled: !isDevMode(),
            registrationStrategy: 'registerWhenStable:30000'
          }),
  ],
};
